//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermaket.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
        }
    
        public string MAKHACHHANG { get; set; }
        public string TENKHACHHANG { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string SDTKH { get; set; }
        public string SOCMND { get; set; }
        public string SOTAIKHOANKH { get; set; }
        public string MASOTHUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
    }
}
